### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "com.intellij.openapi.actionSystem.AnAction.getTemplatePresentation()" because "action" is null

### ISSUE THREAD

**Issue by danny-su** [Mishkun/ataman-intellij#18]
IDE: Clion 2024.3

java.lang.NullPointerException: Cannot invoke "com.intellij.openapi.actionSystem.AnAction.getTemplatePresentation()" because "action" is null
        at io.github.mishkun.ataman.AtamanActionKt.executeAction(AtamanAction.kt:113)
        at io.github.mishkun.ataman.LeaderListStep.onChosen$lambda$1(AtamanAction.kt:98)
        at com.intellij.ui.popup.AbstractPopup.lambda$dispose$21(AbstractPopup.java:1820)
        at com.intellij.openapi.application.WriteIntentReadAction.lambda$run$0(WriteIntentReadAction.java:24)
        at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:128)
        at com.intellij.openapi.application.impl.ApplicationImpl.runWriteIntentReadAction(ApplicationImpl.java:916)
        at com.intellij.openapi.application.WriteIntentReadAction.compute(WriteIntentReadAction.java:55)
        at com.intellij.openapi.application.WriteIntentReadAction.run(WriteIntentReadAction.java:23)
        at com.intellij.openapi.wm.impl.FocusManagerImpl.lambda$doWhenFocusSettlesDown$4(FocusManagerImpl.java:178)
        at com.intellij.util.ui.EdtInvocationManager.invokeLaterIfNeeded(EdtInvocationManager.java:32)
        at com.intellij.ide.IdeEventQueue.executeWhenAllFocusEventsLeftTheQueue(IdeEventQueue.kt:1303)
        at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:173)
        at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:165)
        at com.intellij.ui.popup.AbstractPopup.dispose(AbstractPopup.java:1818)
        at com.intellij.ui.popup.WizardPopup.dispose(WizardPopup.java:170)
        at com.intellij.ui.popup.list.ListPopupImpl.dispose(ListPopupImpl.java:404)
        at com.intellij.openapi.util.ObjectTree.runWithTrace(ObjectTree.java:131)
        at com.intellij.openapi.util.ObjectTree.executeAll(ObjectTree.java:163)
        at com.intellij.openapi.util.Disposer.dispose(Disposer.java:205)
        at com.intellij.openapi.util.Disposer.dispose(Disposer.java:193)
        at com.intellij.ui.popup.WizardPopup.disposeAllParents(WizardPopup.java:278)
        at com.intellij.ui.popup.WizardPopup.disposeAllParents(WizardPopup.java:280)
        at com.intellij.ui.popup.list.ListPopupImpl.disposePopup(ListPopupImpl.java:536)
        at com.intellij.ui.popup.list.ListPopupImpl.handleNextStep(ListPopupImpl.java:560)
        at com.intellij.ui.popup.list.ListPopupImpl._handleSelect(ListPopupImpl.java:521)
        at com.intellij.ui.popup.list.ListPopupImpl.handleSelect(ListPopupImpl.java:446)
        at com.intellij.ui.popup.list.ListPopupImpl$MyMouseListener.mouseReleased(ListPopupImpl.java:786)
        at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:298)
        at java.desktop/java.awt.Component.processMouseEvent(Component.java:6662)
        at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3394)
        at com.intellij.ui.popup.list.ListPopupImpl$MyList.processMouseEvent(ListPopupImpl.java:851)
        at java.desktop/java.awt.Component.processEvent(Component.java:6427)
        at java.desktop/java.awt.Container.processEvent(Container.java:2266)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5032)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4860)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4963)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4577)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4518)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2810)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4860)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:783)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:728)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:98)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:755)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:753)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:752)
        at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:675)
        at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.kt:621)
        at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$21(IdeEventQueue.kt:564)
        at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:128)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:564)
        at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$18$lambda$17$lambda$16$lambda$15(IdeEventQueue.kt:355)
        at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:857)
        at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$18$lambda$17$lambda$16(IdeEventQueue.kt:354)
        at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$2$lambda$1(IdeEventQueue.kt:1045)
        at com.intellij.openapi.application.WriteIntentReadAction.lambda$run$0(WriteIntentReadAction.java:24)
        at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:128)
        at com.intellij.openapi.application.impl.ApplicationImpl.runWriteIntentReadAction(ApplicationImpl.java:916)
        at com.intellij.openapi.application.WriteIntentReadAction.compute(WriteIntentReadAction.java:55)
        at com.intellij.openapi.application.WriteIntentReadAction.run(WriteIntentReadAction.java:23)
        at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$2(IdeEventQueue.kt:1045)
        at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$3(IdeEventQueue.kt:1054)
        at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:117)
        at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1054)
        at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$18(IdeEventQueue.kt:349)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:395)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

**Comment by Mishkun** [comment]
Does it appear on ataman list showing or when you try to execute an action?
